### PR TITLE
A few questions...

### PR DESCRIPTION
**Pull request by tosteiner**
although a bit heavy on OA... some parts borrowed/adapted&remixed from https://blogs.biomedcentral.com/bmcblog/2015/10/22/quiz-test-open-access-knowledge/

### CODE REVIEW

**Comment by Protohedgehog** [comment]
These are really awesome, thanks! Buuuuut, they don't have much to do with Open Source specifically. I would love to pilfer these for quizzes for the other modules though!!

**Comment by tosteiner** [comment]
@Protohedgehog dang, you're right - makes sense to use these for Mod 03 & 06, methinks...  ;) Will try & add more stuff on Open Source later

**Comment by Protohedgehog** [comment]
For now, do you mind if I copy this file over to the OA module? @tosteiner

**Comment by tosteiner** [comment]
@Protohedgehog not at all :)

**Comment by Protohedgehog** [comment]
Done, danke! Added a note to the dev team section there too, just to make sure you get appropriate credit when the time comes.

**Pull request merged**
