### PR TITLE
add continuous integration of hyperlinks checks:testing

### PR DESCRIPTION
**Pull request by jcolomb**
powered via travis

### CODE REVIEW

**Comment by Protohedgehog** [comment]
Er, it seemed to fail the checks @jcolomb ?

**Comment by jcolomb** [comment]
it checked only the readme and failed on redirect links, I used the wrong test, let's see now...

**Comment by jcolomb** [comment]
fail for: 
main.md:
https://open-science-training-handbook.gitbook.io/book/es/02opensciencebasics/03openresearchsoftwareandopensource#knowledge
task2:
https://www.linuxfoundation.org/blog/10-years-of-git-an-interview-with-git-creator-linus-torvalds/
o1-plan.md:
http://www.digitalfreedomfoundation.org/
design:
http://datascienceassn.org/sites/default/files/The%2520Scientific%2520Method%2520in%2520Practice%2520-%2520Reproducibility%2520in%2520the%2520Computational%2520Sciences.pdf
quizz:
https://en.wikipedia.org/wiki/GNU_General_Public_Licensen
keaelenments:
http://datascienceassn.org/sites/default/files/The%2520Scientific%2520Method%2520in%2520Practice%2520-%2520Reproducibility%2520in%2520the%2520Computational%2520Sciences.pdf 
https://cloud.google.com/compute/)(GCE)%2c
module design protocol:
1. [L011] 404 https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Ope  
  2. [L012] 404 https://github.com/OpenScienceMOOC/Module-6-Open-Access-to-Resea  
  3. [L030] 404 https://opensciencemooc.eu/proposed-modules/  
  4. [L037] 404 https://opensciencemooc.eu/about-us/production-team/ 
contribute:
https://twitter.com/OpenSci_MOOC

**Comment by jcolomb** [comment]
made some changes that do not work... cancel pull request

**Pull request closed without merging**
