### PR TITLE
clarification on free/libre vs. OSS; closes #85

### LINKED ISSUE #85: Incorrect description of OSS vs. free/libre software
In the section _The Open Source community and its governance_ it reads:

> The core principle of re-use is what separates OSS from ‘Free Software’.

and:

> The big difference between free software and OSS is that the former must distribute updated versions under the same license as the original, whereas newer versions of OSS can be distributed under different licenses. FOSS combines the best of both worlds.

What I really like about how the module is currently written is that it makes clear that open source is not just about the source being accessible. However, the cited paragraphs are probably misleading in the difference between free software and OSS: It's not about copyleft/re-use. I'll detail that in the following, along with some other suggestions for improvement. The last paragraph contains an idea on how I would explain the difference between free and OSS in this module.

#### Differentiation between software and license

I think it would be better to differentiate more precisely between the software and its license. Free software, [as understood by the FSF](https://www.gnu.org/philosophy/free-sw.html), respects the user's freedom. A necessary requirement is that it is accompanied by a free license, because the default is that all rights stay with the author. [It is probably not the only requirement, as some software under a free license still artificially limits its users (example [here](https://github.com/ONLYOFFICE/DocumentServer/issues/482#issuecomment-456436175)). For now, let's call software under a free license _free_ and software under a open source license _open source_.]

Accordingly, for a software license to be free, the license **does not need** to have a copyleft clause. Take, for example, the MIT license ([Expat](https://directory.fsf.org/wiki/License:Expat) or [X11](https://directory.fsf.org/wiki/License:X11), to be precise): it's not a copyleft license but still a free software license ([source](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses); more about this overlap [here](https://www.gnu.org/philosophy/free-open-overlap.html)).

#### Differentiation between license requirement and license itself

I think the relationship between license requirements and licenses could also be highlighted more: [OSI's OSS definition](https://opensource.org/osd) is a license requirement, as is the [FSF's definition](https://www.gnu.org/philosophy/free-sw.html) of free software (and thus, free software licenses). Various licenses may then be either free, open source, or both. It then can be argued that free _may_ be a subset of open source:

#### Differences between free and open source software

[It is expected](https://www.gnu.org/philosophy/open-source-misses-the-point.html) by the FSF that all free software should also considered OSS by the OSI. For the other way round, there may be cases where this is not true, but _most of the OSS should be free software [as well](https://www.gnu.org/philosophy/free-open-overlap.html)_. If requiring free software over OSS is not so much about the amount of software matching that criteria, what else is it about?

#### Differences between requiring free software vs. OSS

Free software is about protecting the user's freedom. From this perspective, nonfree software is a social problem. OSS instead has a more pragmatic approach, it is centered around the product being better in the end. Nonfree software just cuts efficiency on that road.

This makes clear that requiring free software instead of OSS is about spreading freedom as a value.

#### FOSS

Now, regarding _FOSS_: It's a term derived to cover both OSS and free software. Its practical value may be limited, however, as it only adds to the complexity and stays neutral about the actual difference between the two. I certainly wouldn't call it “the best of both worlds”, which sounds as if _open source_ and _free_ are features that can be meaningful combined—and not philosophies with different goals. Free software _should_ (see above) also be OSS, so the only “best of both worlds” would be to choose free software.

#### Copyleft vs. public domain

While the difference between OSS licenses and free software licenses is not about copyleft clauses, the _copyleft vs. public domain_ conflict may still be worth mentioning.

For someone who believes in the user's freedom, is it better to aim for most permissive licensing (releasing in the public domain) and thus allowing others to limit the users of their derived versions again? Or better make the own work more restrictive in the first place (copyleft), contrary to the higher goal of freedom, but more resistant in the long run?

The OpenStreetMap's wiki has some thoughts about this [here](https://wiki.openstreetmap.org/wiki/Why_would_I_want_my_contributions_to_be_public_domain).

#### Further thoughts

Similar to the comparison between _open source_ and _free_ is that between [Fecher's and Friesike's](https://doi.org/10.1007%2F978-3-319-00026-8_2) _Pragmatic School_ and _Democratic School_: again, it's about (research) efficiency vs. access to knowledge as a means on its own. These different goals and values may still lead to the same practical behavior.

This actually may be the best way to introduce the reader to the differences without adding to much complexity.

Another interesting comparison is that to [Stalder's](https://en.wikipedia.org/wiki/Special:BookSources/978-1-509-51960-6) _Commons_ vs _Post-democracy_, which are about input and output legitimation. But probably not for this guide ;)

### PR DESCRIPTION
**Pull request by fkohrt**

### CODE REVIEW

**Review by geyslein — COMMENTED** [review]
I like the improvements very much. It is very precise on the often confusing differences of both terms/movements oss vs free software. 
The explanations between 153-163 are IMHO a bit too deep for the scope of this module.

**Comment by fkohrt** [comment]
163 has already been written before. Maybe leave out 159-163?

**Comment by dannycolin** [comment]
I second @geyslein :). Also, I really like the parallel made with the two visions of open science.

**Comment by Protohedgehog** [comment]
@fkohrt do you think you could make the slight edits proposed above, and then I can merge this PR? :)

**Comment by Protohedgehog** [comment]
Oh wait you did already...

**Pull request merged**
